<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- Informações do pacote -->
    <PackageId>FCG.BuildingBlocks</PackageId>
    <Version>1.0.1</Version>
    <Authors>Bruno Matos</Authors>
    <Company>Bruno Matos</Company>

    <Title>FCG.BuildingBlocks</Title>

    <Description>
      Biblioteca compartilhada contendo entidades base, enums e eventos de integração utilizados pelos microsserviços da solução FCG (FIAP Cloud Games).
    </Description>

    <PackageTags>
      dotnet;net8;microservices;buildingblocks;ddd;cqrs;cleanarchitecture;fiap
    </PackageTags>

    <!-- Links -->
    <RepositoryUrl>https://github.com/brnmatos/FCG.BuildingBlocks</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

    <PackageProjectUrl>https://github.com/brnmatos/FCG.BuildingBlocks</PackageProjectUrl>

    <!-- Documentação -->
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <!-- Licença -->
    <PackageLicenseExpression>MIT</PackageLicenseExpression>

    <!-- Gerar pacote automaticamente -->
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

    <!-- Símbolos -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>

    <!-- Informações adicionais -->
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>

    <Copyright>
      Copyright © 2026 Bruno Matos
    </Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md"
          Pack="true"
          PackagePath="\" />

    <None Include="LICENSE"
          Pack="true"
          PackagePath="\" />
  </ItemGroup>

</Project>